### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by lug-gh** [mgrela/misc#1]
root@vm:~# python3 vmware.py *** ***

Traceback (most recent call last):
  File "vmware.py", line 25, in <module>
    license_key = esx_dl_page.find("td", string=re.compile("VMware vSphere Hypervisor 6 License")).parent.find_all("td")[1].get_text()
AttributeError: 'NoneType' object has no attribute 'parent'

**Comment by mgrela** [comment]
Hi,

It's possible that you aren't registered for the product. I created a new account just now and it only worked after you registered for the product and accepted the EULA. Script has been updated to detect this kind of scenario, also some other hints were added to help in troubleshooting. It worked just now for me:

$  python3 vmware-esxi-dl.py xxxxx 'xxxx' 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): my.vmware.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /web/vmware/login HTTP/1.1" 302 223
DEBUG:requests.packages.urllib3.connectionpool:"GET /group/vmware/home HTTP/1.1" 302 637
DEBUG:requests.packages.urllib3.connectionpool:"GET /oam/server/obrareq.cgi?encquery%3DY%2BIhkS9bzL5AI6aJvkIZHwhyi%2F0OHiVVf5HRr6MO%2B7Ld7ZC0SAPxVe3SypzMiOakxF%2F5GqHpeVyE36aigz%2ByA0MHrqJieVBgLatnNYcWcHi2FTp%2FJdjMyoRyZD3cQMH2qbiky2eaU9rCTfMhxB6oeN5v%2FZ0JCrR1iBR4OXzOIcZ1IqLxpKUI2cnwXCCwDgSg5jEFJygziHn9OtZ21bh0UGDM3FjUWLsdKFXOfaRYgrhBWcObtQbileHkpbA5QNb8XXgADFKq28sYESowVs1XyD90ySXCU1GzTdm%2F8dRAPjP05XQHVWMcvEmrnP0HYaju%20agentid%3Dweb-prod-wg-sso-vip%20ver%3D1%20crmethod%3D2 HTTP/1.1" 302 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /web/vmware/login?contextType=external&username=string&OverrideRetryLimit=1&action=%2F&password=sercure_string&challenge_url=https%3A%2F%2Fmy.vmware.com%2Fweb%2Fvmware%2Flogin&creds=username+password&request_id=-6728700505475791418&authn_try_count=0&locale=en_US&resource_url=https%253A%252F%252Fmy.vmware.com%252Fgroup%252Fvmware%252Fhome HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"POST /oam/server/auth_cred_submit HTTP/1.1" 302 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /obrar.cgi?encreply=XfCpyDJWo7xm8QFcexTfw8emJ291fe%2FJQFUB64Hx%2BJXG6hG%2FaKmksPCTSSY3KOzTrr%2F8JiADaA0Qy8xBOgsJx%2BSRHzeceCptNakDlB1xiku913uY%2BfwYt6Xvz6qif4cIzDUMan5Z2ygfYN9q7ijAY0p79bRovmzaNSAW9fRRsfKUwmwkMeGYssXJZqb1RubYbMlGm361HWhCxP7AR5inzmrcMgSmMIfU1vGiv1pc3xCVtCRmbVq813alYOT7TTgv%2B17TcWoDjXHBDpWGh7ONlQe5F9uqcsD%2BRGYSUejRkopj9frZP2QVinzc6kmIDlwhcsJotrjhGFxCZGBdSTF2W7mjFlFXamr35PX%2FvsMiobgvc6V5BrI54DyIO%2BbWayl0fgDoOAOyHlYJyNT9Njahdc9u%2BgRXB7GSyDdzFq0htfG8KFCHsHa%2BWyhZpS9rBhcbhp6k9ciFUl%2Bbknb0NyVc4u%2B9P9Cf%2FFl6axfXr07Q1%2BdtElpK8kNOgmx%2FqpFkXO9M7e44JFNxJ%2BoyRPomcp6Hu%2FBfjGqYor4VRdKfjabaq1zDEuuaFSO3WKIvoTv4imX7bmBmyMQNwLUrXekQ6hJhqtVHessm8N1jJwe%2BBCDDtWz5NO1ghVYBPLUdwo1I4sHt%2FF5Ke3bQRTmYhS%2BXCScinebs2S8hXC6XPjqsIzOc7%2BYeAE0mFHLZXaNrd37Iz4kUQsvUWa%2BwXrFGUIzNxqQ8lfodi7peCZtEvEIdj1Knplqvp5cpZ9hN4lW8TRhP00W33C18H6tZO%2F%2B9CcCNzPKDjNqYKXRhuPnustiszR8vgPBfyDkT8FP2kOtcVkrN2xzjQkZQbuUmejAPNEjIR%2FJaVKOQ4%2FiWqFH90QWHtuf%2FOibiwVQnPQ3TiUcYrSybmZgCTI34243SIuqHFUX%2B4SrMW8u5T7I6k89qU7rACCSrbki3bpETiYCZhbHzHPwGR1o4K3go62nv13nXXLHqL4HRA4mQOPNXR6itKgdyETSGdDalKfnlofvsyHRXXZQyiDvY7FFtfRgbxbqSv1VC2Eh0jw%3D%3D HTTP/1.1" 302 202
DEBUG:requests.packages.urllib3.connectionpool:"GET /group/vmware/home HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /en/group/vmware/evalcenter?p=free-esxi6 HTTP/1.1" 200 None
INFO:vmware-esxi-dl.py:Expected checksums: MD5='cee025ba50f118d8b06a8025bd1134d5' SHA1='fbfef38e102543427d4c62f4033cd292999325a8' SHA256='bcbd495b7fdf33796b89bbbe9ef03fcd31f10a943cc30255353565131b7397a9'
DEBUG:requests.packages.urllib3.connectionpool:"GET /en/group/vmware/evalcenter?p_p_id=evalcenter_WAR_itevals_INSTANCE_z9LN&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=evaldownload&p_p_cacheability=cacheLevelPage&p_p_col_id=column-1&p_p_col_count=1&progId=674&a=DOWNLOAD_FILE&baseurl=https://download2.vmware.com/software/esx/65/&filename=VMware-VMvisor-Installer-201701001-4887370.x86_64.iso&popupmode=manual HTTP/1.1" 200 391
INFO:vmware-esxi-dl.py:Downloading image to 'VMware-VMvisor-Installer-201701001-4887370.x86_64.iso'
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): download2.vmware.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /software/esx/65/VMware-VMvisor-Installer-201701001-4887370.x86_64.iso?HashKey=b01f5a1f043d77ed442094f274ddd243&params=%7B%22custnumber%22%3A%22JWQqaHR3dGhqaA%3D%3D%22%2C%22sourcefilesize%22%3A%22328.26+MB%22%2C%22dlgcode%22%3A%22ESXI650A%22%2C%22evaldlgcode%22%3A%22EVAL-FREE-ESXI6-EN-2084%22%2C%22languagecode%22%3A%22en%22%2C%22source%22%3A%22EVALS%22%2C%22downloadtype%22%3A%22manual%22%2C%22downloaduuid%22%3A%2281afe366-b40f-4d56-ac0f-65896d1917ee%22%7D&AuthKey=1486848488_37c8cc3d9fcd63a36328bb21a21aa786 HTTP/1.1" 200 344205312
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
$

**Comment by lug-gh** [comment]
well i just downloaded it from a random persian website, way easier :)
